backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "index.html"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Introduction", name: "intro", widget: "markdown"}
          - {label: "Content", name: "content", widget: "markdown"}
      - label: "About"
        name: "about"
        file: "about.html"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Content", name: "content", widget: "markdown"}
      - label: "Education"
        name: "education"
        file: "education.html"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Education List", name: "education_list", widget: "list", fields: [
                {label: "Degree", name: "degree", widget: "string"},
                {label: "Institution", name: "institution", widget: "string"},
                {label: "Year", name: "year", widget: "string"}
              ]}
      - label: "Projects"
        name: "projects"
        file: "projects.html"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Projects", name: "projects_list", widget: "list", fields: [
                {label: "Project Name", name: "project_name", widget: "string"},
                {label: "Description", name: "description", widget: "markdown"},
                {label: "Link", name: "link", widget: "string"}
              ]}
      - label: "Contact"
        name: "contact"
        file: "contact.html"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Message", name: "message", widget: "text"}
          - {label: "Social Links", name: "social_links", widget: "list", fields: [
                {label: "Platform", name: "platform", widget: "string"},
                {label: "Link", name: "link", widget: "string"}
              ]}
